In [1]:
import pandas as pd

In [2]:
state_df = pd.read_excel("state-of-data-2021.xlsx")
state_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2645 entries, 0 to 2644
Data columns (total 21 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   ID                                          2645 non-null   object
 1   Idade                                       2617 non-null   float64
 2   Faixa idade                                 2645 non-null   object
 3   Genero                                      2645 non-null   object
 4   Estado onde mora                            2609 non-null   object
 5   UF Onde Mora                                2609 non-null   object
 6   Regiao onde mora                            2645 non-null   object
 7   Regiao de origem                            484 non-null    object
 8   Mudou de Estado ?                           2645 non-null   int64
 9   Nivel de Ensino                             2645 non-null   object
 10  Área de Formação                            2581 non-null   object
 11  Qual sua situação atual de trabalho?        2645 non-null   object
 12  Setor                                       2365 non-null   object
 13  Numero de Funcionarios                      2365 non-null   object
 14  Gestor?                                     2365 non-null   float64
 15  Cargo como Gestor                           508 non-null    object
 16  Cargo Atual                                 1857 non-null   object
 17  Nivel                                       1857 non-null   object
 18  Faixa salarial                              2365 non-null   object
 19  Você está satisfeito na sua empresa atual?  2362 non-null   float64
 20  Atualmente qual a sua forma de trabalho?    2365 non-null   object
dtypes: float64(3), int64(1), object(17)
memory usage: 434.1+ KB

In [3]:
state_df_bck = state_df.copy()

In [4]:
## Excluindo a coluna ID

In [5]:
state_df.drop("ID", axis=1, inplace=True)
state_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2645 entries, 0 to 2644
Data columns (total 20 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Idade                                       2617 non-null   float64
 1   Faixa idade                                 2645 non-null   object
 2   Genero                                      2645 non-null   object
 3   Estado onde mora                            2609 non-null   object
 4   UF Onde Mora                                2609 non-null   object
 5   Regiao onde mora                            2645 non-null   object
 6   Regiao de origem                            484 non-null    object
 7   Mudou de Estado ?                           2645 non-null   int64
 8   Nivel de Ensino                             2645 non-null   object
 9   Área de Formação                            2581 non-null   object
 10  Qual sua situação atual de trabalho?        2645 non-null   object
 11  Setor                                       2365 non-null   object
 12  Numero de Funcionarios                      2365 non-null   object
 13  Gestor?                                     2365 non-null   float64
 14  Cargo como Gestor                           508 non-null    object
 15  Cargo Atual                                 1857 non-null   object
 16  Nivel                                       1857 non-null   object
 17  Faixa salarial                              2365 non-null   object
 18  Você está satisfeito na sua empresa atual?  2362 non-null   float64
 19  Atualmente qual a sua forma de trabalho?    2365 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 413.4+ KB

## Alterando a coluna ["Idade"] de float64 par Int64

In [6]:
state_df["Idade"] = pd.to_numeric(state_df["Idade"], errors="coerce")

state_df["Idade"] = state_df["Idade"].astype('Int64')
state_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2645 entries, 0 to 2644
Data columns (total 20 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Idade                                       2617 non-null   Int64
 1   Faixa idade                                 2645 non-null   object
 2   Genero                                      2645 non-null   object
 3   Estado onde mora                            2609 non-null   object
 4   UF Onde Mora                                2609 non-null   object
 5   Regiao onde mora                            2645 non-null   object
 6   Regiao de origem                            484 non-null    object
 7   Mudou de Estado ?                           2645 non-null   int64
 8   Nivel de Ensino                             2645 non-null   object
 9   Área de Formação                            2581 non-null   object
 10  Qual sua situação atual de trabalho?        2645 non-null   object
 11  Setor                                       2365 non-null   object
 12  Numero de Funcionarios                      2365 non-null   object
 13  Gestor?                                     2365 non-null   float64
 14  Cargo como Gestor                           508 non-null    object
 15  Cargo Atual                                 1857 non-null   object
 16  Nivel                                       1857 non-null   object
 17  Faixa salarial                              2365 non-null   object
 18  Você está satisfeito na sua empresa atual?  2362 non-null   float64
 19  Atualmente qual a sua forma de trabalho?    2365 non-null   object
dtypes: Int64(1), float64(2), int64(1), object(16)
memory usage: 416.0+ KB

## Preenchendo a coluna ["Regiao de origem"]

In [7]:
state_df["Regiao de origem"] = state_df["Regiao de origem"].fillna(
    state_df["Regiao onde mora"]
)
state_df["Regiao de origem"]

0       Nordeste
1        Sudeste
2            Sul
3        Sudeste
4            Sul
          ...
2640     Sudeste
2641         Sul
2642         Sul
2643     Sudeste
2644     Sudeste
Name: Regiao de origem, Length: 2645, dtype: object

## Preemchendo a coluna ["Mudou de Estado ?"]

In [8]:
import numpy as np

In [9]:
condicao_mudanca = state_df["Regiao onde mora"] != state_df["Regiao de origem"]
state_df["Mudou de Estado ?"] = np.where(
    condicao_mudanca,
    'Sim',
    'Não'
)
state_df["Mudou de Estado ?"]

0       Não
1       Sim
2       Não
3       Não
4       Não
       ...
2640    Não
2641    Não
2642    Não
2643    Não
2644    Não
Name: Mudou de Estado ?, Length: 2645, dtype: object

## Verificando os valores nulos da coluna ["Regiao de origem"]

In [12]:
contagem_nulos = state_df["Regiao de origem"].isnull().sum()

print(f"Total de valores nulos em 'Regiao de origem': {contagem_nulos}")

Total de valores nulos em 'Regiao de origem': 0

In [16]:
state_df["Regiao de origem"] = state_df["Regiao de origem"].fillna(
    state_df["Regiao onde mora"]
)

## Excluindo valores nulos das colunas ["Idade", "Faixa salarial"]

In [18]:
valores_nulos = ["Idade", "Faixa salarial"]
print(valores_nulos)

['Idade', 'Faixa salarial']

In [20]:
state_df = state_df.dropna(subset=valores_nulos)
state_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2341 entries, 0 to 2642
Data columns (total 20 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Idade                                       2341 non-null   Int64
 1   Faixa idade                                 2341 non-null   object
 2   Genero                                      2341 non-null   object
 3   Estado onde mora                            2315 non-null   object
 4   UF Onde Mora                                2315 non-null   object
 5   Regiao onde mora                            2341 non-null   object
 6   Regiao de origem                            2341 non-null   object
 7   Mudou de Estado ?                           2341 non-null   object
 8   Nivel de Ensino                             2341 non-null   object
 9   Área de Formação                            2288 non-null   object
 10  Qual sua situação atual de trabalho?        2341 non-null   object
 11  Setor                                       2341 non-null   object
 12  Numero de Funcionarios                      2341 non-null   object
 13  Gestor?                                     2341 non-null   float64
 14  Cargo como Gestor                           496 non-null    object
 15  Cargo Atual                                 1845 non-null   object
 16  Nivel                                       1845 non-null   object
 17  Faixa salarial                              2341 non-null   object
 18  Você está satisfeito na sua empresa atual?  2338 non-null   float64
 19  Atualmente qual a sua forma de trabalho?    2341 non-null   object
dtypes: Int64(1), float64(2), object(17)
memory usage: 386.4+ KB

## Salário por faixa etária

In [21]:
salario_por_faixa_etaria = state_df.groupby(["Faixa idade", "Faixa salarial"]).size().unstack(fill_value=0)
print(salario_por_faixa_etaria)

Faixa salarial  Acima de R$ 40.001/mês  Menos de R$ 1.000/mês  \
Faixa idade
17-21                                0                      8
22-24                                0                      8
25-29                                5                      9
30-34                               11                      2
35-39                               12                      1
40-44                                5                      0
45-49                                1                      0
50-54                                0                      2

Faixa salarial  de R$ 1.001/mês a R$ 2.000/mês  \
Faixa idade
17-21                                       26
22-24                                       44
25-29                                       32
30-34                                       12
35-39                                        6
40-44                                        3
45-49                                        2
50-54                                        1

Faixa salarial  de R$ 12.001/mês a R$ 16.000/mês  \
Faixa idade
17-21                                          1
22-24                                          4
25-29                                         69
30-34                                         87
35-39                                         49
40-44                                         23
45-49                                         21
50-54                                          8

Faixa salarial  de R$ 16.001/mês a R$ 20.000/mês  \
Faixa idade
17-21                                          0
22-24                                          1
25-29                                         32
30-34                                         38
35-39                                         28
40-44                                         14
45-49                                          7
50-54                                          7

Faixa salarial  de R$ 2.001/mês a R$ 3000/mês  \
Faixa idade
17-21                                      24
22-24                                      46
25-29                                      53
30-34                                      38
35-39                                      11
40-44                                       6
45-49                                       2
50-54                                       0

Faixa salarial  de R$ 20.001/mês a R$ 25.000/mês  \
Faixa idade
17-21                                          0
22-24                                          2
25-29                                         15
30-34                                          9
35-39                                         16
40-44                                          6
45-49                                          6
50-54                                          5

Faixa salarial  de R$ 25.001/mês a R$ 30.000/mês  \
Faixa idade
17-21                                          0
22-24                                          0
25-29                                          8
30-34                                         10
35-39                                         10
40-44                                          8
45-49                                          3
50-54                                          2

Faixa salarial  de R$ 3.001/mês a R$ 4.000/mês  \
Faixa idade
17-21                                        5
22-24                                       39
25-29                                       68
30-34                                       44
35-39                                       17
40-44                                        4
45-49                                        3
50-54                                        2

Faixa salarial  de R$ 30.001/mês a R$ 40.000/mês  \
Faixa idade
17-21                                          0
22-24                                          1
25-29                                          5
30-34                                         12
35-39                                          6
40-44                                         10
45-49                                          4
50-54                                          0

Faixa salarial  de R$ 4.001/mês a R$ 6.000/mês  \
Faixa idade
17-21                                       10
22-24                                       64
25-29                                      152
30-34                                       77
35-39                                       56
40-44                                       27
45-49                                        8
50-54                                        5

Faixa salarial  de R$ 6.001/mês a R$ 8.000/mês  \
Faixa idade
17-21                                        4
22-24                                       37
25-29                                      147
30-34                                      112
35-39                                       45
40-44                                       27
45-49                                       11
50-54                                        6

Faixa salarial  de R$ 8.001/mês a R$ 12.000/mês
Faixa idade
17-21                                         1
22-24                                        34
25-29                                       163
30-34                                       126
35-39                                        78
40-44                                        41
45-49                                        14
50-54                                        17

## Salário por região

In [22]:
salario_por_regiao = state_df.groupby(["Regiao onde mora", "Faixa salarial"]).size().unstack(fill_value=0)
print(salario_por_regiao)

Faixa salarial    Acima de R$ 40.001/mês  Menos de R$ 1.000/mês  \
Regiao onde mora
Centro-oeste                           0                      2
Exterior                               6                      0
Nordeste                               2                     10
Norte                                  0                      2
Sudeste                               22                     13
Sul                                    4                      3

Faixa salarial    de R$ 1.001/mês a R$ 2.000/mês  \
Regiao onde mora
Centro-oeste                                  10
Exterior                                       1
Nordeste                                      21
Norte                                          1
Sudeste                                       75
Sul                                           18

Faixa salarial    de R$ 12.001/mês a R$ 16.000/mês  \
Regiao onde mora
Centro-oeste                                    26
Exterior                                         4
Nordeste                                        18
Norte                                            2
Sudeste                                        179
Sul                                             33

Faixa salarial    de R$ 16.001/mês a R$ 20.000/mês  \
Regiao onde mora
Centro-oeste                                    17
Exterior                                         3
Nordeste                                         5
Norte                                            0
Sudeste                                         83
Sul                                             19

Faixa salarial    de R$ 2.001/mês a R$ 3000/mês  \
Regiao onde mora
Centro-oeste                                 13
Exterior                                      1
Nordeste                                     20
Norte                                         3
Sudeste                                     123
Sul                                          20

Faixa salarial    de R$ 20.001/mês a R$ 25.000/mês  \
Regiao onde mora
Centro-oeste                                     4
Exterior                                         4
Nordeste                                         3
Norte                                            1
Sudeste                                         38
Sul                                              9

Faixa salarial    de R$ 25.001/mês a R$ 30.000/mês  \
Regiao onde mora
Centro-oeste                                     5
Exterior                                         1
Nordeste                                         4
Norte                                            0
Sudeste                                         29
Sul                                              2

Faixa salarial    de R$ 3.001/mês a R$ 4.000/mês  \
Regiao onde mora
Centro-oeste                                   8
Exterior                                       1
Nordeste                                      23
Norte                                          4
Sudeste                                      111
Sul                                           35

Faixa salarial    de R$ 30.001/mês a R$ 40.000/mês  \
Regiao onde mora
Centro-oeste                                     3
Exterior                                         6
Nordeste                                         1
Norte                                            1
Sudeste                                         25
Sul                                              2

Faixa salarial    de R$ 4.001/mês a R$ 6.000/mês  \
Regiao onde mora
Centro-oeste                                  27
Exterior                                       5
Nordeste                                      57
Norte                                          4
Sudeste                                      234
Sul                                           72

Faixa salarial    de R$ 6.001/mês a R$ 8.000/mês  \
Regiao onde mora
Centro-oeste                                  19
Exterior                                       1
Nordeste                                      37
Norte                                          5
Sudeste                                      257
Sul                                           70

Faixa salarial    de R$ 8.001/mês a R$ 12.000/mês
Regiao onde mora
Centro-oeste                                   34
Exterior                                        7
Nordeste                                       37
Norte                                           3
Sudeste                                       316
Sul                                            77

## Salário por gênero

In [23]:
salario_por_genero = state_df.groupby(["Genero", "Faixa salarial"]).size().unstack(fill_value=0)
print(salario_por_genero)

Faixa salarial  Acima de R$ 40.001/mês  Menos de R$ 1.000/mês  \
Genero
Feminino                             3                      5
Masculino                           31                     25
Outro                                0                      0

Faixa salarial  de R$ 1.001/mês a R$ 2.000/mês  \
Genero
Feminino                                    23
Masculino                                  102
Outro                                        1

Faixa salarial  de R$ 12.001/mês a R$ 16.000/mês  \
Genero
Feminino                                      34
Masculino                                    228
Outro                                          0

Faixa salarial  de R$ 16.001/mês a R$ 20.000/mês  \
Genero
Feminino                                      16
Masculino                                    111
Outro                                          0

Faixa salarial  de R$ 2.001/mês a R$ 3000/mês  \
Genero
Feminino                                   40
Masculino                                 140
Outro                                       0

Faixa salarial  de R$ 20.001/mês a R$ 25.000/mês  \
Genero
Feminino                                       8
Masculino                                     51
Outro                                          0

Faixa salarial  de R$ 25.001/mês a R$ 30.000/mês  \
Genero
Feminino                                       4
Masculino                                     37
Outro                                          0

Faixa salarial  de R$ 3.001/mês a R$ 4.000/mês  \
Genero
Feminino                                    39
Masculino                                  143
Outro                                        0

Faixa salarial  de R$ 30.001/mês a R$ 40.000/mês  \
Genero
Feminino                                       3
Masculino                                     34
Outro                                          1

Faixa salarial  de R$ 4.001/mês a R$ 6.000/mês  \
Genero
Feminino                                    83
Masculino                                  313
Outro                                        3

Faixa salarial  de R$ 6.001/mês a R$ 8.000/mês  \
Genero
Feminino                                    80
Masculino                                  309
Outro                                        0

Faixa salarial  de R$ 8.001/mês a R$ 12.000/mês
Genero
Feminino                                     96
Masculino                                   378
Outro                                         0

## Salário por região do gênero masculino

In [26]:
df_masculino = state_df[state_df["Genero"] == "Masculino"]

salario_regiao_masc_abs = df_masculino.groupby(
    ["Regiao onde mora", "Faixa salarial"]
).size().unstack(fill_value=0)
print(salario_regiao_masc_abs)

Faixa salarial    Acima de R$ 40.001/mês  Menos de R$ 1.000/mês  \
Regiao onde mora
Centro-oeste                           0                      2
Exterior                               6                      0
Nordeste                               2                      7
Norte                                  0                      2
Sudeste                               19                     11
Sul                                    4                      3

Faixa salarial    de R$ 1.001/mês a R$ 2.000/mês  \
Regiao onde mora
Centro-oeste                                   8
Exterior                                       1
Nordeste                                      15
Norte                                          1
Sudeste                                       65
Sul                                           12

Faixa salarial    de R$ 12.001/mês a R$ 16.000/mês  \
Regiao onde mora
Centro-oeste                                    21
Exterior                                         2
Nordeste                                        17
Norte                                            2
Sudeste                                        154
Sul                                             32

Faixa salarial    de R$ 16.001/mês a R$ 20.000/mês  \
Regiao onde mora
Centro-oeste                                    15
Exterior                                         3
Nordeste                                         5
Norte                                            0
Sudeste                                         70
Sul                                             18

Faixa salarial    de R$ 2.001/mês a R$ 3000/mês  \
Regiao onde mora
Centro-oeste                                 12
Exterior                                      0
Nordeste                                     19
Norte                                         2
Sudeste                                      88
Sul                                          19

Faixa salarial    de R$ 20.001/mês a R$ 25.000/mês  \
Regiao onde mora
Centro-oeste                                     4
Exterior                                         4
Nordeste                                         2
Norte                                            1
Sudeste                                         31
Sul                                              9

Faixa salarial    de R$ 25.001/mês a R$ 30.000/mês  \
Regiao onde mora
Centro-oeste                                     5
Exterior                                         1
Nordeste                                         3
Norte                                            0
Sudeste                                         26
Sul                                              2

Faixa salarial    de R$ 3.001/mês a R$ 4.000/mês  \
Regiao onde mora
Centro-oeste                                   8
Exterior                                       1
Nordeste                                      22
Norte                                          3
Sudeste                                       84
Sul                                           25

Faixa salarial    de R$ 30.001/mês a R$ 40.000/mês  \
Regiao onde mora
Centro-oeste                                     2
Exterior                                         5
Nordeste                                         1
Norte                                            1
Sudeste                                         23
Sul                                              2

Faixa salarial    de R$ 4.001/mês a R$ 6.000/mês  \
Regiao onde mora
Centro-oeste                                  26
Exterior                                       4
Nordeste                                      42
Norte                                          3
Sudeste                                      184
Sul                                           54

Faixa salarial    de R$ 6.001/mês a R$ 8.000/mês  \
Regiao onde mora
Centro-oeste                                  15
Exterior                                       1
Nordeste                                      33
Norte                                          4
Sudeste                                      199
Sul                                           57

Faixa salarial    de R$ 8.001/mês a R$ 12.000/mês
Regiao onde mora
Centro-oeste                                   29
Exterior                                        7
Nordeste                                       31
Norte                                           3
Sudeste                                       245
Sul                                            63

## Salário por região do gênero feminio

In [27]:
df_feminino = state_df[state_df["Genero"] == "Feminino"]

salario_regiao_fem_abs = df_feminino.groupby(
    ["Regiao onde mora", "Faixa salarial"]
).size().unstack(fill_value=0)
print(salario_regiao_fem_abs)

Faixa salarial    Acima de R$ 40.001/mês  Menos de R$ 1.000/mês  \
Regiao onde mora
Centro-oeste                           0                      0
Exterior                               0                      0
Nordeste                               0                      3
Norte                                  0                      0
Sudeste                                3                      2
Sul                                    0                      0

Faixa salarial    de R$ 1.001/mês a R$ 2.000/mês  \
Regiao onde mora
Centro-oeste                                   2
Exterior                                       0
Nordeste                                       6
Norte                                          0
Sudeste                                       10
Sul                                            5

Faixa salarial    de R$ 12.001/mês a R$ 16.000/mês  \
Regiao onde mora
Centro-oeste                                     5
Exterior                                         2
Nordeste                                         1
Norte                                            0
Sudeste                                         25
Sul                                              1

Faixa salarial    de R$ 16.001/mês a R$ 20.000/mês  \
Regiao onde mora
Centro-oeste                                     2
Exterior                                         0
Nordeste                                         0
Norte                                            0
Sudeste                                         13
Sul                                              1

Faixa salarial    de R$ 2.001/mês a R$ 3000/mês  \
Regiao onde mora
Centro-oeste                                  1
Exterior                                      1
Nordeste                                      1
Norte                                         1
Sudeste                                      35
Sul                                           1

Faixa salarial    de R$ 20.001/mês a R$ 25.000/mês  \
Regiao onde mora
Centro-oeste                                     0
Exterior                                         0
Nordeste                                         1
Norte                                            0
Sudeste                                          7
Sul                                              0

Faixa salarial    de R$ 25.001/mês a R$ 30.000/mês  \
Regiao onde mora
Centro-oeste                                     0
Exterior                                         0
Nordeste                                         1
Norte                                            0
Sudeste                                          3
Sul                                              0

Faixa salarial    de R$ 3.001/mês a R$ 4.000/mês  \
Regiao onde mora
Centro-oeste                                   0
Exterior                                       0
Nordeste                                       1
Norte                                          1
Sudeste                                       27
Sul                                           10

Faixa salarial    de R$ 30.001/mês a R$ 40.000/mês  \
Regiao onde mora
Centro-oeste                                     1
Exterior                                         0
Nordeste                                         0
Norte                                            0
Sudeste                                          2
Sul                                              0

Faixa salarial    de R$ 4.001/mês a R$ 6.000/mês  \
Regiao onde mora
Centro-oeste                                   0
Exterior                                       1
Nordeste                                      14
Norte                                          1
Sudeste                                       49
Sul                                           18

Faixa salarial    de R$ 6.001/mês a R$ 8.000/mês  \
Regiao onde mora
Centro-oeste                                   4
Exterior                                       0
Nordeste                                       4
Norte                                          1
Sudeste                                       58
Sul                                           13

Faixa salarial    de R$ 8.001/mês a R$ 12.000/mês
Regiao onde mora
Centro-oeste                                    5
Exterior                                        0
Nordeste                                        6
Norte                                           0
Sudeste                                        71
Sul                                            14