In [1]:
import pandas as pd

## Criar um DataFrame para cada ano

In [2]:
df_2016 =  pd.read_csv("compras-e-licitacoes-2016.csv")

In [3]:
df_2017 =  pd.read_csv("compras-e-licitacoes-2017.csv")

In [4]:
df_2018 = pd.read_csv("compras-e-licitacoes-2018.csv")

In [5]:
df_2019 = pd.read_csv("compras-e-licitacoes-2019.csv")

In [6]:
df_2020 = pd.read_csv("compras-e-licitacoes-2020.csv")

## Criar um DataFrame com todos os anos

In [7]:
total_df = pd.concat([df_2016, df_2017, df_2018, df_2019, df_2020])
total_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1304 entries, 0 to 81
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Órgão Sup UResp Compra ID      1304 non-null   int64
 1   Órgão Vinc UResp Compra DESC   1304 non-null   object
 2   Órgão UResp Compra ID          1304 non-null   int64
 3   Órgão UResp Compra DESC        1304 non-null   object
 4   Cod UResp Compra DESC          1304 non-null   int64
 5   Cod UResp Compra NOME          1304 non-null   object
 6   UF UResp Compra DESC           1304 non-null   object
 7   Municipio UResp Compra DESC    1304 non-null   object
 8   Número Processo Compra DESC    1304 non-null   object
 9   Modalidade Compra DESC         1304 non-null   object
 10  Identif Compra DESC            1304 non-null   int64
 11  Tipo Licitação DESC            1304 non-null   object
 12  Inciso Disp Legal DESC         1304 non-null   object
 13  Forma Compra DESC              1304 non-null   object
 14  Objeto Compra DESC             1304 non-null   object
 15  Dia Abert Sessão Publ ID       1304 non-null   object
 16  Sit Atual Compra DESC          1304 non-null   object
 17  Existência Result Compra DESC  1304 non-null   object
 18  Dia Homologação Compra DESC    950 non-null    object
 19  Sub-rogação Compra DESC        1304 non-null   object
 20  Valor Total Homologado         1304 non-null   object
 21  Ano Resultado Compra DESC      354 non-null    float64
 22  Dia Homologação Compra ID      354 non-null    object
dtypes: float64(1), int64(4), object(18)
memory usage: 244.5+ KB

## Criar uma copia do DataFrame Original

In [8]:
total__bck_df = total_df.copy()

## Converter as Datas que estão como Object para DateTime
	Dia Abert Sessão Publ ID
	Dia Homologação Compra DESC
	Dia Homologação Compra ID

In [9]:
for colunas_data in [
    'Dia Abert Sessão Publ ID',
    'Dia Homologação Compra DESC',
    'Dia Homologação Compra ID',
]:
    total_df[colunas_data] = pd.to_datetime(total_df[colunas_data], errors='coerce')
    total_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1304 entries, 0 to 81
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Órgão Sup UResp Compra ID      1304 non-null   int64
 1   Órgão Vinc UResp Compra DESC   1304 non-null   object
 2   Órgão UResp Compra ID          1304 non-null   int64
 3   Órgão UResp Compra DESC        1304 non-null   object
 4   Cod UResp Compra DESC          1304 non-null   int64
 5   Cod UResp Compra NOME          1304 non-null   object
 6   UF UResp Compra DESC           1304 non-null   object
 7   Municipio UResp Compra DESC    1304 non-null   object
 8   Número Processo Compra DESC    1304 non-null   object
 9   Modalidade Compra DESC         1304 non-null   object
 10  Identif Compra DESC            1304 non-null   int64
 11  Tipo Licitação DESC            1304 non-null   object
 12  Inciso Disp Legal DESC         1304 non-null   object
 13  Forma Compra DESC              1304 non-null   object
 14  Objeto Compra DESC             1304 non-null   object
 15  Dia Abert Sessão Publ ID       408 non-null    datetime64[ns]
 16  Sit Atual Compra DESC          1304 non-null   object
 17  Existência Result Compra DESC  1304 non-null   object
 18  Dia Homologação Compra DESC    950 non-null    object
 19  Sub-rogação Compra DESC        1304 non-null   object
 20  Valor Total Homologado         1304 non-null   object
 21  Ano Resultado Compra DESC      354 non-null    float64
 22  Dia Homologação Compra ID      354 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(4), object(17)
memory usage: 244.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1304 entries, 0 to 81
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Órgão Sup UResp Compra ID      1304 non-null   int64
 1   Órgão Vinc UResp Compra DESC   1304 non-null   object
 2   Órgão UResp Compra ID          1304 non-null   int64
 3   Órgão UResp Compra DESC        1304 non-null   object
 4   Cod UResp Compra DESC          1304 non-null   int64
 5   Cod UResp Compra NOME          1304 non-null   object
 6   UF UResp Compra DESC           1304 non-null   object
 7   Municipio UResp Compra DESC    1304 non-null   object
 8   Número Processo Compra DESC    1304 non-null   object
 9   Modalidade Compra DESC         1304 non-null   object
 10  Identif Compra DESC            1304 non-null   int64
 11  Tipo Licitação DESC            1304 non-null   object
 12  Inciso Disp Legal DESC         1304 non-null   object
 13  Forma Compra DESC              1304 non-null   object
 14  Objeto Compra DESC             1304 non-null   object
 15  Dia Abert Sessão Publ ID       408 non-null    datetime64[ns]
 16  Sit Atual Compra DESC          1304 non-null   object
 17  Existência Result Compra DESC  1304 non-null   object
 18  Dia Homologação Compra DESC    771 non-null    datetime64[ns]
 19  Sub-rogação Compra DESC        1304 non-null   object
 20  Valor Total Homologado         1304 non-null   object
 21  Ano Resultado Compra DESC      354 non-null    float64
 22  Dia Homologação Compra ID      354 non-null    object
dtypes: datetime64[ns](2), float64(1), int64(4), object(16)
memory usage: 244.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1304 entries, 0 to 81
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Órgão Sup UResp Compra ID      1304 non-null   int64
 1   Órgão Vinc UResp Compra DESC   1304 non-null   object
 2   Órgão UResp Compra ID          1304 non-null   int64
 3   Órgão UResp Compra DESC        1304 non-null   object
 4   Cod UResp Compra DESC          1304 non-null   int64
 5   Cod UResp Compra NOME          1304 non-null   object
 6   UF UResp Compra DESC           1304 non-null   object
 7   Municipio UResp Compra DESC    1304 non-null   object
 8   Número Processo Compra DESC    1304 non-null   object
 9   Modalidade Compra DESC         1304 non-null   object
 10  Identif Compra DESC            1304 non-null   int64
 11  Tipo Licitação DESC            1304 non-null   object
 12  Inciso Disp Legal DESC         1304 non-null   object
 13  Forma Compra DESC              1304 non-null   object
 14  Objeto Compra DESC             1304 non-null   object
 15  Dia Abert Sessão Publ ID       408 non-null    datetime64[ns]
 16  Sit Atual Compra DESC          1304 non-null   object
 17  Existência Result Compra DESC  1304 non-null   object
 18  Dia Homologação Compra DESC    771 non-null    datetime64[ns]
 19  Sub-rogação Compra DESC        1304 non-null   object
 20  Valor Total Homologado         1304 non-null   object
 21  Ano Resultado Compra DESC      354 non-null    float64
 22  Dia Homologação Compra ID      354 non-null    datetime64[ns]
dtypes: datetime64[ns](3), float64(1), int64(4), object(15)
memory usage: 244.5+ KB

/tmp/ipython-input-2733754590.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  total_df[colunas_data] = pd.to_datetime(total_df[colunas_data], errors='coerce')
/tmp/ipython-input-2733754590.py:6: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  total_df[colunas_data] = pd.to_datetime(total_df[colunas_data], errors='coerce')

## Converter os numeros que estão como Object para to_number
	Valor Total Homologado

In [10]:
from numpy import e
# Removendo ponto milhar
total_df["Valor Total Homologado"] = total_df["Valor Total Homologado"].astype(str).str.replace('.', '', regex=False)

# Trocando vírgula decimal por ponto
total_df["Valor Total Homologado"] = total_df["Valor Total Homologado"].str.replace(',', '.', regex=False)

# Convertando object em float64
total_df["Valor Total Homologado"] = pd.to_numeric(total_df["Valor Total Homologado"], errors='coerce')
total_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1304 entries, 0 to 81
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Órgão Sup UResp Compra ID      1304 non-null   int64
 1   Órgão Vinc UResp Compra DESC   1304 non-null   object
 2   Órgão UResp Compra ID          1304 non-null   int64
 3   Órgão UResp Compra DESC        1304 non-null   object
 4   Cod UResp Compra DESC          1304 non-null   int64
 5   Cod UResp Compra NOME          1304 non-null   object
 6   UF UResp Compra DESC           1304 non-null   object
 7   Municipio UResp Compra DESC    1304 non-null   object
 8   Número Processo Compra DESC    1304 non-null   object
 9   Modalidade Compra DESC         1304 non-null   object
 10  Identif Compra DESC            1304 non-null   int64
 11  Tipo Licitação DESC            1304 non-null   object
 12  Inciso Disp Legal DESC         1304 non-null   object
 13  Forma Compra DESC              1304 non-null   object
 14  Objeto Compra DESC             1304 non-null   object
 15  Dia Abert Sessão Publ ID       408 non-null    datetime64[ns]
 16  Sit Atual Compra DESC          1304 non-null   object
 17  Existência Result Compra DESC  1304 non-null   object
 18  Dia Homologação Compra DESC    771 non-null    datetime64[ns]
 19  Sub-rogação Compra DESC        1304 non-null   object
 20  Valor Total Homologado         1304 non-null   float64
 21  Ano Resultado Compra DESC      354 non-null    float64
 22  Dia Homologação Compra ID      354 non-null    datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(4), object(14)
memory usage: 244.5+ KB

## Converter o float64 para Inter64
	Ano Resultado Compra DESC

In [11]:
# Transforma o conteúdo da coluna em números, sem erro
total_df["Ano Resultado Compra DESC"] = pd.to_numeric(total_df["Ano Resultado Compra DESC"], errors='coerce')

# Transforma o conteúdo da coluna de float64 em Int64
total_df["Ano Resultado Compra DESC"] = total_df["Ano Resultado Compra DESC"].astype('Int64')
total_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1304 entries, 0 to 81
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Órgão Sup UResp Compra ID      1304 non-null   int64
 1   Órgão Vinc UResp Compra DESC   1304 non-null   object
 2   Órgão UResp Compra ID          1304 non-null   int64
 3   Órgão UResp Compra DESC        1304 non-null   object
 4   Cod UResp Compra DESC          1304 non-null   int64
 5   Cod UResp Compra NOME          1304 non-null   object
 6   UF UResp Compra DESC           1304 non-null   object
 7   Municipio UResp Compra DESC    1304 non-null   object
 8   Número Processo Compra DESC    1304 non-null   object
 9   Modalidade Compra DESC         1304 non-null   object
 10  Identif Compra DESC            1304 non-null   int64
 11  Tipo Licitação DESC            1304 non-null   object
 12  Inciso Disp Legal DESC         1304 non-null   object
 13  Forma Compra DESC              1304 non-null   object
 14  Objeto Compra DESC             1304 non-null   object
 15  Dia Abert Sessão Publ ID       408 non-null    datetime64[ns]
 16  Sit Atual Compra DESC          1304 non-null   object
 17  Existência Result Compra DESC  1304 non-null   object
 18  Dia Homologação Compra DESC    771 non-null    datetime64[ns]
 19  Sub-rogação Compra DESC        1304 non-null   object
 20  Valor Total Homologado         1304 non-null   float64
 21  Ano Resultado Compra DESC      354 non-null    Int64
 22  Dia Homologação Compra ID      354 non-null    datetime64[ns]
dtypes: Int64(1), datetime64[ns](3), float64(1), int64(4), object(14)
memory usage: 245.8+ KB

## Criando uma coluna "Ano" para verificar os gastos anuais
	Dia Homologação Compra DESC

In [12]:
# Criar uma nova coluna no DataFrame somente com o Ano  do dia da homologação
homologacao_ano = "Dia Homologação Compra DESC"

# Transformando a data em um número que pode ser usado como chave de agrupamento.
total_df[homologacao_ano] = pd.to_datetime(total_df[homologacao_ano], errors='coerce', dayfirst=True)

# Garantindo que o número seja inteiro (2016 - 2020)
total_df['Ano'] = total_df[homologacao_ano].dt.year.astype('Int64')
total_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1304 entries, 0 to 81
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Órgão Sup UResp Compra ID      1304 non-null   int64
 1   Órgão Vinc UResp Compra DESC   1304 non-null   object
 2   Órgão UResp Compra ID          1304 non-null   int64
 3   Órgão UResp Compra DESC        1304 non-null   object
 4   Cod UResp Compra DESC          1304 non-null   int64
 5   Cod UResp Compra NOME          1304 non-null   object
 6   UF UResp Compra DESC           1304 non-null   object
 7   Municipio UResp Compra DESC    1304 non-null   object
 8   Número Processo Compra DESC    1304 non-null   object
 9   Modalidade Compra DESC         1304 non-null   object
 10  Identif Compra DESC            1304 non-null   int64
 11  Tipo Licitação DESC            1304 non-null   object
 12  Inciso Disp Legal DESC         1304 non-null   object
 13  Forma Compra DESC              1304 non-null   object
 14  Objeto Compra DESC             1304 non-null   object
 15  Dia Abert Sessão Publ ID       408 non-null    datetime64[ns]
 16  Sit Atual Compra DESC          1304 non-null   object
 17  Existência Result Compra DESC  1304 non-null   object
 18  Dia Homologação Compra DESC    771 non-null    datetime64[ns]
 19  Sub-rogação Compra DESC        1304 non-null   object
 20  Valor Total Homologado         1304 non-null   float64
 21  Ano Resultado Compra DESC      354 non-null    Int64
 22  Dia Homologação Compra ID      354 non-null    datetime64[ns]
 23  Ano                            771 non-null    Int64
dtypes: Int64(2), datetime64[ns](3), float64(1), int64(4), object(14)
memory usage: 257.2+ KB

## Retirando os valores nulos da coluna "Ano"

In [13]:
total_df.dropna(subset=['Ano'], inplace=True)
total_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 771 entries, 1 to 315
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Órgão Sup UResp Compra ID      771 non-null    int64
 1   Órgão Vinc UResp Compra DESC   771 non-null    object
 2   Órgão UResp Compra ID          771 non-null    int64
 3   Órgão UResp Compra DESC        771 non-null    object
 4   Cod UResp Compra DESC          771 non-null    int64
 5   Cod UResp Compra NOME          771 non-null    object
 6   UF UResp Compra DESC           771 non-null    object
 7   Municipio UResp Compra DESC    771 non-null    object
 8   Número Processo Compra DESC    771 non-null    object
 9   Modalidade Compra DESC         771 non-null    object
 10  Identif Compra DESC            771 non-null    int64
 11  Tipo Licitação DESC            771 non-null    object
 12  Inciso Disp Legal DESC         771 non-null    object
 13  Forma Compra DESC              771 non-null    object
 14  Objeto Compra DESC             771 non-null    object
 15  Dia Abert Sessão Publ ID       53 non-null     datetime64[ns]
 16  Sit Atual Compra DESC          771 non-null    object
 17  Existência Result Compra DESC  771 non-null    object
 18  Dia Homologação Compra DESC    771 non-null    datetime64[ns]
 19  Sub-rogação Compra DESC        771 non-null    object
 20  Valor Total Homologado         771 non-null    float64
 21  Ano Resultado Compra DESC      0 non-null      Int64
 22  Dia Homologação Compra ID      0 non-null      datetime64[ns]
 23  Ano                            771 non-null    Int64
dtypes: Int64(2), datetime64[ns](3), float64(1), int64(4), object(14)
memory usage: 152.1+ KB

In [14]:
total_df["Ano"]

1      2016
4      2016
5      2016
7      2016
8      2016
       ...
311    1900
312    1900
313    1900
314    1900
315    1900
Name: Ano, Length: 771, dtype: Int64

## Eliminado anos anterios a 2016

In [15]:
# Definindo as condições
ano_min = total_df["Ano"] >= 2016
ano_max = total_df["Ano"] <= 2020

# Combinando as condições (E lógico, representado pelo &)
ano_valido = ano_min & ano_max

In [20]:
total_df = total_df[
    (total_df["Ano"] >= 2016) &
    (total_df["Ano"] <= 2020)
]

In [21]:
total_df.info()
total_df["Ano"]

<class 'pandas.core.frame.DataFrame'>
Index: 124 entries, 1 to 302
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Órgão Sup UResp Compra ID      124 non-null    int64
 1   Órgão Vinc UResp Compra DESC   124 non-null    object
 2   Órgão UResp Compra ID          124 non-null    int64
 3   Órgão UResp Compra DESC        124 non-null    object
 4   Cod UResp Compra DESC          124 non-null    int64
 5   Cod UResp Compra NOME          124 non-null    object
 6   UF UResp Compra DESC           124 non-null    object
 7   Municipio UResp Compra DESC    124 non-null    object
 8   Número Processo Compra DESC    124 non-null    object
 9   Modalidade Compra DESC         124 non-null    object
 10  Identif Compra DESC            124 non-null    int64
 11  Tipo Licitação DESC            124 non-null    object
 12  Inciso Disp Legal DESC         124 non-null    object
 13  Forma Compra DESC              124 non-null    object
 14  Objeto Compra DESC             124 non-null    object
 15  Dia Abert Sessão Publ ID       53 non-null     datetime64[ns]
 16  Sit Atual Compra DESC          124 non-null    object
 17  Existência Result Compra DESC  124 non-null    object
 18  Dia Homologação Compra DESC    124 non-null    datetime64[ns]
 19  Sub-rogação Compra DESC        124 non-null    object
 20  Valor Total Homologado         124 non-null    float64
 21  Ano Resultado Compra DESC      0 non-null      Int64
 22  Dia Homologação Compra ID      0 non-null      datetime64[ns]
 23  Ano                            124 non-null    Int64
dtypes: Int64(2), datetime64[ns](3), float64(1), int64(4), object(14)
memory usage: 24.5+ KB

1      2016
4      2016
5      2016
7      2016
8      2016
       ...
254    2018
277    2017
289    2018
301    2018
302    2018
Name: Ano, Length: 124, dtype: Int64

## Gastos por ano

In [30]:
gastos_por_ano = total_df.groupby("Ano")["Valor Total Homologado"].sum()
pd.options.display.float_format = 'R$ {:,.2f}'.format
display(gastos_por_ano)

Ano
2016   R$ 21,268,715.10
2017   R$ 17,906,471.94
2018   R$ 12,007,145.29
Name: Valor Total Homologado, dtype: float64

## Gastos por Município

In [36]:
gastos_por_municipio = total_df.groupby("Municipio UResp Compra DESC")["Valor Total Homologado"].sum()
display(gastos_por_municipio)

Municipio UResp Compra DESC
ARIQUEMES            R$ 5,759,588.12
CACOAL                 R$ 857,611.00
COLORADO DO OESTE   R$ 12,145,212.93
GUAJARA-MIRIM          R$ 760,532.80
JI-PARANA            R$ 5,455,910.07
PORTO VELHO         R$ 23,562,032.34
VILHENA              R$ 2,641,445.07
Name: Valor Total Homologado, dtype: float64

## Gastos por Município por Ano

In [29]:
gastos_municipio_ano = total_df.groupby(["Municipio UResp Compra DESC", "Ano"])["Valor Total Homologado"].sum()
display(gastos_municipio_ano)

Municipio UResp Compra DESC  Ano
ARIQUEMES                    2016   R$ 1,130,499.47
                             2017   R$ 4,145,062.66
                             2018     R$ 484,025.99
CACOAL                       2016     R$ 117,664.84
                             2017     R$ 244,522.45
                             2018     R$ 495,423.71
COLORADO DO OESTE            2016   R$ 5,243,651.33
                             2017   R$ 4,286,416.89
                             2018   R$ 2,615,144.71
GUAJARA-MIRIM                2017     R$ 542,136.36
                             2018     R$ 218,396.44
JI-PARANA                    2016   R$ 4,440,305.20
                             2017      R$ 79,142.12
                             2018     R$ 936,462.76
PORTO VELHO                  2016   R$ 7,738,636.11
                             2017   R$ 8,596,928.68
                             2018   R$ 7,226,467.55
VILHENA                      2016   R$ 2,597,958.16
                             2017      R$ 12,262.78
                             2018      R$ 31,224.13
Name: Valor Total Homologado, dtype: float64

## Maior Gasto

In [34]:
indice_maximo = total_df["Valor Total Homologado"].idxmax()

registro_maximo = total_df.loc[indice_maximo]

resultado = registro_maximo[["Municipio UResp Compra DESC", "Ano", "Valor Total Homologado"]]
display(resultado)

Municipio UResp Compra DESC       PORTO VELHO
Ano                                      2018
Valor Total Homologado        R$ 3,358,542.00
Name: 0, dtype: object

## Menor Gasto

In [37]:
indice_minimo = total_df["Valor Total Homologado"].idxmin()

registro_minimo = total_df.loc[indice_minimo]
resultado = registro_minimo[["Municipio UResp Compra DESC", "Ano", "Valor Total Homologado"]]
display(resultado)

Municipio UResp Compra DESC    ARIQUEMES
Ano                                 2016
Valor Total Homologado           R$ 0.00
Name: 181, dtype: object